# Generated by Django 2.0.7 on 2018-08-01 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='material_inti',
            field=models.CharField(choices=[('COAL', 'COAL'), ('OB', 'OB')], default='COAL', max_length=50),
        ),
        migrations.AlterField(
            model_name='material',
            name='submaterial',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='worker',
            name='tipe_pekerja',
            field=models.CharField(choices=[('OPERATOR', 'Operator'), ('DRIVER', 'Driver')], default='DRIVER', max_length=140),
        ),
    ]
